### ISSUE TITLE
Picture does not appear anywhere

### ISSUE THREAD

**Issue by DBinaghi** [GonCuesMa/CollectionFiles#1]
Hi.
I've installed your plugin, loaded a picture in a Collection and then.. nothing: the picture does not appear anywhere, neither on Admin nor on Public side.
Besides, if I try editing the picture, the Admin side is displaying a very long array of Dublin Core metadata, instead of normal editing page.
Omeka version: 2.8

**Comment by GonCuesMa** [comment]
@DBinaghi First of all, apologies for the delayed response.

I have already fixed all bugs related to the admin area.

Collection View
![Screenshot-20210522120739-1004x712](https://user-images.githubusercontent.com/61585305/119222930-0ba54100-baf7-11eb-8e03-3349b9433143.png)
Edit View
![Screenshot-20210522120806-1004x663](https://user-images.githubusercontent.com/61585305/119222933-0d6f0480-baf7-11eb-82d7-d8e8361fa4e5.png)
Collection Browse View
![Screenshot-20210522120829-1008x372](https://user-images.githubusercontent.com/61585305/119222938-152ea900-baf7-11eb-83c5-abf00525f2a3.png)

Regarding the public side, if you want to display collection files, you would have to modify your personal theme.

Thanks for opening this issue!
Regards.
