### ISSUE TITLE
Collection_id not found when creating a new Collection AND uploading a file

### ISSUE THREAD

**Issue by DBinaghi** [GonCuesMa/CollectionFiles#2]
Hi.
I've tested the actual version of the files, but plugin throws an error if trying to create a new Collection while at the same time uploading a file in it; the same problem does not appear when editing an existing collection.

Here's the error message:
Zend_Db_Statement_Mysqli_Exception: Mysqli statement execute error : Column 'collection_id' cannot be null in /home/wearewaa/public_html/application/libraries/Zend/Db/Statement/Mysqli.php:215
Stack trace:
#0 /home/wearewaa/public_html/application/libraries/Zend/Db/Statement.php(303): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /home/wearewaa/public_html/application/libraries/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 /home/wearewaa/public_html/application/libraries/Omeka/Db.php(80): Zend_Db_Adapter_Abstract->query('INSERT INTO `om...', Array)
#3 /home/wearewaa/public_html/application/libraries/Omeka/Db.php(257): Omeka_Db->__call('query', Array)
#4 /home/wearewaa/public_html/application/libraries/Omeka/Record/AbstractRecord.php(541): Omeka_Db->insert('om_collection_f...', Array)
#5 /home/wearewaa/public_html/plugins/CollectionFiles/CollectionFilesPlugin.php(177): Omeka_Record_AbstractRecord->save()
#6 /home/wearewaa/public_html/plugins/CollectionFiles/CollectionFilesPlugin.php(159): CollectionFilesPlugin->insert_files_for_collection(Object(Collection), 'Upload', Array, Array)
#7 /home/wearewaa/public_html/application/libraries/Omeka/Plugin/Broker.php(154): CollectionFilesPlugin->hookBeforeSaveCollection(Array)
#8 /home/wearewaa/public_html/application/libraries/Omeka/Record/AbstractRecord.php(301): Omeka_Plugin_Broker->callHook('before_save_col...', Array)
#9 /home/wearewaa/public_html/application/libraries/Omeka/Record/AbstractRecord.php(529): Omeka_Record_AbstractRecord->runCallbacks('beforeSave', Array)
#10 /home/wearewaa/public_html/application/libraries/Omeka/Controller/AbstractActionController.php(188): Omeka_Record_AbstractRecord->save(false)
#11 /home/wearewaa/public_html/application/controllers/CollectionsController.php(42): Omeka_Controller_AbstractActionController->addAction()
#12 /home/wearewaa/public_html/application/libraries/Zend/Controller/Action.php(516): CollectionsController->addAction()
#13 /home/wearewaa/public_html/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('addAction')
#14 /home/wearewaa/public_html/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#15 /home/wearewaa/public_html/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#16 /home/wearewaa/public_html/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#17 /home/wearewaa/public_html/application/libraries/Omeka/Application.php(73): Zend_Application->run()
#18 /home/wearewaa/public_html/admin/index.php(28): Omeka_Application->run()
#19 {main}

Hope this helps.

**Comment by GonCuesMa** [comment]
Hi @DBinaghi! Thanks for reporting this bug :+1: 
I believe everything should be working now so I am resolving for now. If you find other issues, feel free to reopen.

Thanks!
